### ISSUE TITLE
Clean UP & Dockerization eos8h6g

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8h6g#2]

**Comment by samuelmaina** [comment]
HI @GemmaTuron  and @simrantan   
Model fetches success with fetch test smiles having output vals, however the model seems to work with input files but fail to predict for single smiles.  It is not even showing the  the key and the text vals of the input  on single input. 
The  error of singles is consistent in cli, colab and docker.   Full null logs : [eos8h6g_1_smiles_pred.log](https://github.com/ersilia-os/eos8h6g/files/11971452/eos8h6g_1_smiles_pred.log)

```
{
    "input": {
        "key": null,
        "input": null,
        "text": null
    },
    "output": {
        "fp": [
            null,
            null,
```
- CLI
   - [eos8h6g_cli_fetch.log](https://github.com/ersilia-os/eos8h6g/files/11971382/eos8h6g_cli_fetch.log)
   - [eos8h6g_cli_pred.csv](https://github.com/ersilia-os/eos8h6g/files/11971385/eos8h6g_cli_pred.csv)
- Colab
    - [colab_eos8h6g_fetch.log](https://github.com/ersilia-os/eos8h6g/files/11971398/colab_eos8h6g_fetch.log)
    - [eos8h6g_colab_output.csv](https://github.com/ersilia-os/eos8h6g/files/11971402/eos8h6g_colab_output.csv)
-  Docker
   - [eml_eos8h6g_docker.csv](https://github.com/ersilia-os/eos8h6g/files/11971416/eml_eos8h6g_docker.csv)

```
~samuelmayna : ~/ersilia_github_models/eos8h6g (main) $ docker run -v /home/samuelmayna:/data  ersiliaos/eos8h6g
+ [ -z eos8h6g ]
+ ersilia serve -p 3000 eos8h6g
🚀 Serving model eos8h6g: avalon

   URL: http://127.0.0.1:3000
   PID: 35
   SRV: conda

👉 To run model:
   - run

💁 Information:
   - info
Serving model eos8h6g...
+ echo Serving model eos8h6g...
+ nginx -g daemon off;
```
```
Error: No such option: -i
root@ad4b63270011:/data# ersilia run  -i eos8h6g/eml_canonical.csv -o eos8h6g_docker_emL_pred.csv
eos8h6g_docker_emL_pred.csv
root@ad4b63270011:/data# 
```
